name: e_lib
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_multi_select_items: ^0.4.3
  flutter_pdfview: ^1.3.2
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.0
  logger: ^2.3.0
  pdfx: ^2.6.0
  persistent_bottom_nav_bar: ^5.0.2
  scroll_to_hide: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Sedan
      fonts:
        - asset: assets/fonts/Sedan/Sedan-Regular.ttf
        - asset: assets/fonts/Sedan/Sedan-italic.ttf
          style: italic
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis/Dosis-Regular.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf  
    - family: Help 
      fonts:    
        - asset: assets/fonts/Help.ttf    
  assets:
    - assets/cover_imgs/
    - assets/logo/
    - assets/images/
    - assets/books/Atomichabits.pdf

  uses-material-design: true
